# Generated by Django 2.0.3 on 2018-03-07 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code du patient')),
                ('date_depot', models.DateField(default=datetime.datetime(2018, 3, 7, 19, 46, 12, 4368, tzinfo=utc), verbose_name='date du depôt du dossier')),
                ('date_maj', models.DateField(auto_now_add=True, verbose_name='date de mise à jour du dossier')),
                ('traitement', models.TextField(verbose_name='Traitement médical')),
                ('Remarque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarque')),
                ('attestation_droit', models.NullBooleanField(verbose_name="Attestation d'ouverture des droits")),
                ('debut_validite', models.DateField(blank=True, null=True, verbose_name="Début de valditié de l'attestation")),
                ('fin_validite', models.DateField(blank=True, null=True, verbose_name="Fin de valditié de l'attestation")),
                ('photocopies', models.BooleanField(default=True, verbose_name='Photocopie')),
                ('extrait_naissance', models.BooleanField(default=False, verbose_name="extrait de naissance de l'enfant")),
                ('kafala', models.BooleanField(default=True, verbose_name='Kafala')),
                ('fiche_familiale', models.BooleanField(default=True, verbose_name='Fiche familiale')),
                ('telethorax', models.DateField(blank=True, null=True, verbose_name='Téléthorax')),
                ('ecg', models.DateField(blank=True, null=True, verbose_name='ECG')),
                ('ett', models.DateField(blank=True, null=True, verbose_name='Echocoeur')),
                ('epreuve_effort', models.DateField(blank=True, null=True, verbose_name="épreuve d'effort")),
                ('stress_echo', models.DateField(blank=True, null=True, verbose_name='Stress-echo')),
                ('scintigraphie', models.DateField(blank=True, null=True, verbose_name='Scintigraphie myocardique')),
                ('coroscan', models.DateField(blank=True, null=True, verbose_name='Coroscanner')),
                ('doppler_tsa', models.DateField(blank=True, null=True, verbose_name='Doppler des TSA')),
                ('doppler_mi', models.DateField(blank=True, null=True, verbose_name='Doppler des MI')),
                ('echo_abdom', models.DateField(blank=True, null=True, verbose_name='échographie abdominale')),
                ('efr', models.DateField(blank=True, null=True, verbose_name='EFR')),
                ('stomato', models.DateField(blank=True, null=True, verbose_name='Expertise dentaire')),
                ('glycemie', models.DateField(blank=True, null=True, verbose_name='Glycémie')),
                ('hba1c', models.DateField(blank=True, null=True, verbose_name='Hemoglobine glycquée')),
                ('coro_repport', models.DateField(blank=True, null=True, verbose_name='CD + compte rendu de coro')),
                ('uree_creat', models.DateField(blank=True, null=True, verbose_name='Urée - Créatinine')),
                ('lipidogramme', models.DateField(blank=True, null=True, verbose_name='Lipidogramme')),
                ('crp', models.DateField(blank=True, null=True, verbose_name='CRP')),
                ('vs', models.DateField(blank=True, null=True, verbose_name='VS')),
                ('tp_inr', models.DateField(blank=True, null=True, verbose_name='TP - INR')),
                ('tca', models.DateField(blank=True, null=True, verbose_name='TCA')),
                ('groupage', models.DateField(blank=True, null=True, verbose_name='Groupage phénotypé')),
                ('hiv', models.DateField(blank=True, null=True, verbose_name='Sérologie HIV')),
                ('hcv', models.DateField(blank=True, null=True, verbose_name='Sérologie HCV')),
                ('hbv', models.DateField(blank=True, null=True, verbose_name='Sérologie HBV')),
                ('rejet', models.DateField(blank=True, null=True, verbose_name='Rejeté le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte', models.CharField(max_length=50, verbose_name='acte médical')),
                ('codification', models.CharField(blank=True, max_length=6, null=True, verbose_name='codification')),
                ('tarif', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte', models.CharField(max_length=100, verbose_name='Acte médical')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
            ],
        ),
        migrations.AddField(
            model_name='convention',
            name='quotation',
            field=models.ManyToManyField(blank=True, null=True, to='billing.Quotation'),
        ),
    ]
