# Generated by Django 2.0.3 on 2018-03-07 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180307_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 3, 7, 19, 57, 1, 270693, tzinfo=utc), verbose_name='date du depôt du dossier'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='codification',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='codification'),
        ),
    ]
