# Generated by Django 2.0.3 on 2018-03-07 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180307_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 3, 7, 21, 30, 33, 538764, tzinfo=utc), verbose_name='date du depôt du dossier'),
        ),
    ]
