# Generated by Django 2.0.3 on 2018-03-08 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20180307_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='attestation_droit',
            field=models.NullBooleanField(verbose_name='Attestation ouverture droits'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code patient'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 3, 8, 20, 47, 52, 198888, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='date_maj',
            field=models.DateField(auto_now_add=True, verbose_name='date MAJ  dossier'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='debut_validite',
            field=models.DateField(blank=True, null=True, verbose_name='Début de validité attestation'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='extrait_naissance',
            field=models.BooleanField(default=False, verbose_name='extrait de naissance enfant'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='fin_validite',
            field=models.DateField(blank=True, null=True, verbose_name='Fin  validité attestation'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='rejet',
            field=models.DateField(blank=True, null=True, verbose_name='Rejet le'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='traitement',
            field=models.TextField(verbose_name='Traitement'),
        ),
    ]
