# Generated by Django 2.0.3 on 2018-03-08 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20180308_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 3, 8, 20, 50, 20, 28842, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
