# Generated by Django 2.0.3 on 2018-03-23 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20180320_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 318342, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
