# Generated by Django 2.0.3 on 2018-04-03 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20180324_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 3, 21, 8, 42, 890983, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
