# Generated by Django 2.0.3 on 2018-04-12 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_auto_20180412_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 12, 17, 57, 23, 803259, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
