# Generated by Django 2.0.3 on 2018-04-13 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_auto_20180412_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 11, 16, 24, 614769, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
