# Generated by Django 2.0.4 on 2018-04-19 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_auto_20180413_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 19, 19, 20, 56, 555541, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
