# Generated by Django 2.0.4 on 2018-04-23 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20180419_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 7, 53, 18, 955445, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
