# Generated by Django 2.0.4 on 2018-04-23 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_auto_20180423_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 9, 30, 1, 887609, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
