# Generated by Django 2.0.4 on 2018-04-25 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_auto_20180425_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 25, 18, 19, 23, 693290, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
