# Generated by Django 2.0.4 on 2018-04-26 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_auto_20180425_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 17, 5, 30, 469150, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
