# Generated by Django 2.0.4 on 2018-04-26 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_auto_20180426_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 17, 7, 15, 486096, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
