# Generated by Django 2.0.4 on 2018-04-26 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_auto_20180426_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 20, 56, 5, 918308, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
