# Generated by Django 2.0.4 on 2018-05-27 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_auto_20180426_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date_depot',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 10, 54, 16, 564994, tzinfo=utc), verbose_name='date depôt dossier'),
        ),
    ]
