# Generated by Django 2.0.4 on 2018-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronarographie',
            name='atropine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Atropine'),
        ),
        migrations.AddField(
            model_name='coronarographie',
            name='ballon',
            field=models.ManyToManyField(blank=True, to='cathlab.Ballon'),
        ),
        migrations.AddField(
            model_name='coronarographie',
            name='heparin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='héparine'),
        ),
        migrations.AddField(
            model_name='coronarographie',
            name='loxen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Loxen'),
        ),
        migrations.AddField(
            model_name='coronarographie',
            name='medecin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='médecin demandeur'),
        ),
        migrations.AddField(
            model_name='coronarographie',
            name='nitro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Risordan'),
        ),
    ]
