# Generated by Django 2.0.3 on 2018-03-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180307_2230'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date du rendez-vous')),
                ('planned', models.NullBooleanField(default=True, verbose_name='patient programmé')),
                ('confirmed', models.NullBooleanField(default=False, verbose_name='Confirmé')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='numéro du patient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='clinic.Patient')),
                ('prestation', models.ManyToManyField(blank=True, null=True, to='billing.Prestation')),
            ],
        ),
    ]
