# Generated by Django 2.0.3 on 2018-03-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_reception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='prestation',
            new_name='prestations',
        ),
    ]
