# Generated by Django 2.0.3 on 2018-03-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20180308_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='reduction',
            field=models.NullBooleanField(default=False, verbose_name='réduction'),
        ),
    ]
