# Generated by Django 2.0.3 on 2018-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20180308_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du rendez-vous'),
        ),
    ]
