# Generated by Django 2.0.3 on 2018-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20180308_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='n°'),
        ),
    ]
