# Generated by Django 2.0.3 on 2018-03-24 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0009_auto_20180320_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name="date de l'admission")),
                ('emergency', models.BooleanField(default=False, verbose_name='urgence')),
                ('med_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin reférent')),
                ('unity', models.CharField(choices=[('1', 'salles 1er'), ('2', 'salles 2ème'), ('3', 'USIC'), ('4', 'réanimation')], default='1', max_length=1, verbose_name="unité d'hospitalisation")),
                ('chambre', models.CharField(blank=True, max_length=5, verbose_name='Chambre')),
                ('fever', models.BooleanField(default=False, verbose_name='fièvre')),
                ('dyspnea_nyha', models.PositiveSmallIntegerField(default='1', verbose_name='stade NYHA')),
                ('angina_scc', models.PositiveSmallIntegerField(default='1', verbose_name="stade d'angor")),
                ('syncope', models.BooleanField(default=False, verbose_name='Syncope')),
                ('histoire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Histoire de la maladie')),
                ('etat_general', models.CharField(blank=True, max_length=255, verbose_name="état à l'admision")),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('auscultation', models.CharField(blank=True, max_length=100, null=True)),
                ('ivg', models.BooleanField(default=False, verbose_name="signes d'IVG")),
                ('ivd', models.BooleanField(default=False, verbose_name="signes d'IVD")),
                ('tsj', models.BooleanField(default=False, verbose_name='Turguscence des jugulaires')),
                ('rhj', models.BooleanField(default=False, verbose_name='reflux hpato-jugulaire')),
                ('omi', models.BooleanField(default=False, verbose_name='oedèmes des MI')),
                ('pulse', models.CharField(blank=True, max_length=50)),
                ('telethorax', models.CharField(blank=True, max_length=50, null=True)),
                ('rythm', models.CharField(blank=True, choices=[('S', 'Sinusal'), ('F', 'Atrial Fibrillation'), ('R', 'Atrial Flutter'), ('P', 'Pace Maker'), ('T', 'TV')], max_length=1, null=True, verbose_name='rythme')),
                ('freq', models.PositiveSmallIntegerField(default='70', verbose_name='fréquence cardiaque')),
                ('bundle_block', models.CharField(blank=True, choices=[('D', 'BBD'), ('G', 'BBG')], max_length=1, verbose_name='Bloc de branche')),
                ('hypertrophy', models.CharField(blank=True, choices=[('G', 'HVG'), ('D', 'HVD')], max_length=1, verbose_name='Hypertrophie ventriculaire')),
                ('necrosis', models.CharField(blank=True, choices=[('N', 'absence'), ('S', 'septal'), ('A', 'antérieur'), ('L', 'latéral'), ('P', 'posterieur')], max_length=1, null=True)),
                ('ischaemia', models.CharField(blank=True, choices=[('N', 'absence'), ('S', 'septal'), ('A', 'antérieur'), ('L', 'latéral'), ('P', 'posterieur')], max_length=1, null=True)),
                ('lesion', models.CharField(blank=True, choices=[('N', 'absence'), ('S', 'septal'), ('A', 'antérieur'), ('L', 'latéral'), ('P', 'posterieur')], max_length=1, null=True)),
                ('t_inversion', models.CharField(blank=True, choices=[('N', 'absence'), ('S', 'septal'), ('A', 'antérieur'), ('L', 'latéral'), ('P', 'posterieur')], max_length=1, null=True)),
                ('corrected_qt', models.IntegerField(default=400)),
                ('echocoeur', models.TextField(blank=True, null=True, verbose_name='échocardiographie')),
                ('date_echo', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'écho")),
                ('eto', models.TextField(blank=True, null=True, verbose_name='échocardiographie trans-oesophagienne')),
                ('fevg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FeVG')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé clinique')),
                ('evolution', models.TextField(blank=True, verbose_name='Evolution')),
                ('sortant', models.NullBooleanField(verbose_name='Sortant')),
                ('sortie_date', models.DateField(null=True, verbose_name='Date de sortie')),
                ('dispositions', models.CharField(blank=True, max_length=255, verbose_name='dispositions complémentaires')),
                ('ordonnance', models.TextField(blank=True, null=True, verbose_name='Ordonnance')),
                ('medecin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motif_admission', models.ManyToManyField(to='clinic.Motif')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clinic.Patient')),
            ],
        ),
    ]
