# Generated by Django 2.0.3 on 2018-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(choices=[('F', 'fonctionnaire'), ('E', 'employé'), ('C', 'commerçant'), ('R', 'retraité'), ('Y', 'femme au foyer'), ('T', 'étudiant'), ('D', 'cadre'), ('L', 'profession libérale'), ('O', 'au chômage')], max_length=1, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='stress',
            name='disposition',
            field=models.CharField(choices=[('M', 'Traitement médical'), ('C', 'Coronarographie diagnostique'), ('R', 'Coronarographie et éventuel geste de revascularisation'), ('N', 'Non concluante'), ('O', 'indication opératoire')], default='M', max_length=1, verbose_name='Dispositions complémentaires'),
        ),
    ]
