# Generated by Django 2.0.3 on 2018-04-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20180407_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='syntax',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SYNTAX score'),
        ),
    ]
