# Generated by Django 2.0.3 on 2018-04-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20180407_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originaires', to='clinic.Wilaya', verbose_name='lieu de naisssance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demeurants', to='clinic.Wilaya'),
        ),
    ]
