# Generated by Django 2.0.3 on 2018-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_auto_20180407_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='taille_og',
            field=models.CharField(blank=True, max_length=255, verbose_name="Taille et vacuité de l'OG"),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='vd',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fonction VD'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assurance',
            field=models.CharField(choices=[('N', 'CNAS'), ('S', 'CASNOS'), ('A', 'Autre'), ('O', 'Non assuré')], default='N', max_length=1, verbose_name='Assurance sociale'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, choices=[('F', 'fonctionnaire'), ('E', 'employé'), ('C', 'commerçant'), ('R', 'retraité'), ('Y', 'femme au foyer'), ('T', 'étudiant'), ('S', 'scolarisé'), ('D', 'cadre'), ('L', 'profession libérale'), ('O', 'au chômage')], max_length=1, verbose_name='Profession'),
        ),
    ]
