# Generated by Django 2.0.3 on 2018-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20180407_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='calcemia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='calcémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='creatinin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='créatininémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='ferretin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ferritinémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='fibrinogen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='fibrinogénémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='glycemia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='HBA1c'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hbv',
            field=models.NullBooleanField(verbose_name='sérologie HBS'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hcv',
            field=models.NullBooleanField(verbose_name='sérologie HCV'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hdl',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='héoglobinémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='hiv',
            field=models.NullBooleanField(verbose_name='sérologie HIV'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='ldl',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='platlets',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='plaquettes'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='tp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TP'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='triglyceride',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='uremia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='urémie'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='wbc',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='globules blancs'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='dfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fonction rénale (DFG)'),
        ),
    ]
