# Generated by Django 2.0.3 on 2018-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20180412_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='decision',
            field=models.CharField(blank=True, max_length=255, verbose_name='décision du médecin traitant'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='hdl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='ldl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='triglyceride',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
