# Generated by Django 2.0.3 on 2018-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_auto_20180413_1216'),
        ('clinic', '0018_auto_20180412_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='quotation',
            field=models.ManyToManyField(blank=True, null=True, to='billing.Quotation'),
        ),
    ]
