# Generated by Django 2.0.4 on 2018-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_auto_20180423_0853'),
        ('clinic', '0019_fichetechnique_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichetechnique',
            name='quotation',
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='quotation1',
            field=models.ManyToManyField(blank=True, null=True, related_name='q1', to='billing.Quotation'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='quotation2',
            field=models.ManyToManyField(blank=True, null=True, related_name='q2', to='billing.Quotation'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='quotation3',
            field=models.ManyToManyField(blank=True, null=True, related_name='q3', to='billing.Quotation'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='calcemia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='calcémie (mg/l)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='clearance_cr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fonction rénale (clearance ml/min)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='creatinin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='créatininémie mg/l'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='dfg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fonction rénale (DFG ml/min/1.73m2)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='fibrinogen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='fibrinogénémie (g/l)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='glycemia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='glucémie g/l'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='HBA1c %'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='héoglobinémie (g/dl)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='platlets',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='plaquettes (1000elt/mm3)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='tp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TP %'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='uremia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='urémie (g/l)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='wbc',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='globules blancs (1000elt/mm3)'),
        ),
    ]
