# Generated by Django 2.0.4 on 2018-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_auto_20180423_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='wbc',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='globules blancs (elt/mm3)'),
        ),
    ]
