# Generated by Django 2.0.4 on 2018-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_auto_20180423_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wilaya',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='crp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CRP (mg/l)'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='vs_h1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='VS H1 (mm)'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='vs_h2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='VS H2 (mm)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='ferretin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ferritinémie'),
        ),
    ]
