# Generated by Django 2.0.4 on 2018-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_auto_20180527_1154'),
        ('clinic', '0027_fichetechnique_paps'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='quotation4',
            field=models.ManyToManyField(blank=True, related_name='q4', to='billing.Quotation'),
        ),
    ]
