# Generated by Django 2.0.3 on 2018-03-09 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0008_auto_20180309_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arret_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 371585, tzinfo=utc), verbose_name='Date du début')),
                ('type_arret', models.CharField(choices=[('A', 'arrêt de travail'), ('P', 'prolongation'), ('R', 'reprise')], max_length=1, verbose_name='Type de certifict')),
                ('duree', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='durée')),
                ('redaction_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 371654, tzinfo=utc), verbose_name='délivré le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correspondant')),
                ('certificat_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 369579, tzinfo=utc), verbose_name='Date')),
                ('motif', models.CharField(blank=True, max_length=100, null=True, verbose_name='clinic.Motif')),
                ('declaration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Déclare que')),
                ('closing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Closing')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correspondant')),
                ('correspondant_adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse du correspondant')),
                ('salutation', models.CharField(choices=[('C', 'Cher confrère'), ('A', 'Cher ami'), ('S', 'Chère consoeur'), ('B', 'Cher confrère, chère consoeur'), ('M', 'Cher maître')], default='C', max_length=1, verbose_name='Salutation')),
                ('courrier_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 370185, tzinfo=utc), verbose_name='Date')),
                ('reponse', models.BooleanField(default=False)),
                ('diagnostic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motif')),
                ('declaration', models.TextField(blank=True, null=True, verbose_name="l'examen retrouve")),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conclusion')),
                ('closing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Closing')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordonnance_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 367778, tzinfo=utc), verbose_name='Date')),
                ('medoc1', models.CharField(blank=True, max_length=50, null=True)),
                ('poso1', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp1', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc2', models.CharField(blank=True, max_length=50, null=True)),
                ('poso2', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp2', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc3', models.CharField(blank=True, max_length=50, null=True)),
                ('poso3', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp3', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc4', models.CharField(blank=True, max_length=50, null=True)),
                ('poso4', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp4', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc5', models.CharField(blank=True, max_length=50, null=True)),
                ('poso5', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp5', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc6', models.CharField(blank=True, max_length=50, null=True)),
                ('poso6', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp6', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc7', models.CharField(blank=True, max_length=50, null=True)),
                ('poso7', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp7', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc8', models.CharField(blank=True, max_length=50, null=True)),
                ('poso8', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp8', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc9', models.CharField(blank=True, max_length=50, null=True)),
                ('poso9', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp9', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc10', models.CharField(blank=True, max_length=50, null=True)),
                ('poso10', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp10', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc11', models.CharField(blank=True, max_length=50, null=True)),
                ('poso11', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp11', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc12', models.CharField(blank=True, max_length=50, null=True)),
                ('poso12', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp12', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc13', models.CharField(blank=True, max_length=50, null=True)),
                ('poso13', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp13', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc14', models.CharField(blank=True, max_length=50, null=True)),
                ('poso14', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp14', models.CharField(blank=True, max_length=10, null=True)),
                ('medoc15', models.CharField(blank=True, max_length=50, null=True)),
                ('poso15', models.CharField(blank=True, max_length=25, null=True)),
                ('qsp15', models.CharField(blank=True, max_length=25, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Stomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stomato_date', models.DateField(default=datetime.datetime(2018, 3, 9, 7, 24, 25, 370864, tzinfo=utc), verbose_name='Date')),
                ('diagnostic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnostic')),
                ('infectious_risk', models.CharField(choices=[('F', 'faible'), ('M', 'modéré'), ('I', 'important')], default='F', max_length=1, verbose_name='Risque infectieux')),
                ('thrombotic_risk', models.CharField(choices=[('F', 'faible'), ('M', 'modéré'), ('I', 'important')], default='F', max_length=1, verbose_name='Risque thrombo-embolique')),
                ('syncopal_risk', models.CharField(choices=[('F', 'faible'), ('M', 'modéré'), ('I', 'important')], default='F', max_length=1, verbose_name='Risque syncopal')),
                ('inr_cible', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='INR Cible')),
                ('avk_interruption', models.NullBooleanField()),
                ('atb', models.NullBooleanField(default=False, verbose_name='antibioprophylaxie')),
                ('atb_therapie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Antbiothérapie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
            ],
        ),
    ]
