# Generated by Django 2.0.3 on 2018-03-23 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_auto_20180320_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='stomato',
            name='dentist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dentiste'),
        ),
        migrations.AddField(
            model_name='stomato',
            name='dentist_adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse du dentiste'),
        ),
        migrations.AddField(
            model_name='stomato',
            name='lovenox',
            field=models.PositiveSmallIntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='stomato',
            name='salutation',
            field=models.CharField(choices=[('C', 'Cher confrère'), ('A', 'Cher ami'), ('S', 'Chère consoeur'), ('B', 'Cher confrère, chère consoeur'), ('M', 'Cher maître')], default='C', max_length=1, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='arret',
            name='arret_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 350105, tzinfo=utc), verbose_name='Date du début'),
        ),
        migrations.AlterField(
            model_name='arret',
            name='redaction_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 350175, tzinfo=utc), verbose_name='délivré le'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='certificat_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 347876, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='courrier_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 348554, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='ordonnance_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 345946, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stomato',
            name='stomato_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 0, 13, 6, 349249, tzinfo=utc), verbose_name='Date'),
        ),
    ]
